@echo off
rem Build cipher static lib and run unit tests (Windows Visual C++ required in PATH)
setlocal
echo Building cipher object files...
cl /nologo /c /EHsc /MD "Cipher\CaesarCipher.cpp" "Cipher\AffineCipher.cpp" || exit /b 1
echo Creating CipherLib.lib...
lib /nologo /OUT:CipherLib.lib CaesarCipher.obj AffineCipher.obj || exit /b 1
echo Building test executable...
cl /nologo /EHsc /MD "tests\TestCiphers.cpp" CipherLib.lib /link /OUT:TestCiphers.exe || exit /b 1
echo Running tests...
TestCiphers.exe
endlocal
